version: '3'
services:
    jobscraper:
        image: varunbhat/jobscraper
        entrypoint: bash /scripts/start_crawl.sh
        build: .
        volumes:
            - ./joblister:/src
            - ./scripts:/scripts
